
import { CreatorItem } from '../../../types';
import { DEFAULT_COVER } from '../../constants';

export const episodes: CreatorItem[] = [
  // --- 2026 ---
  {
    id: '2026-1',
    shareRank: 1,
    title: 'All in AI 的第一个三年',
    guest: '绿洲资本合伙人 张津剑',
    description: '在智谱和 MiniMax 相继上市之后，这一波 AI 也算完整经历了第一个小周期。在这期节目里，曲老师和津剑共同复盘了 AI 的第一个三年。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/s_L2EIZ8biy89X4VVmsknQ',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/6961bd3af8b05f9f75c3edb8?utm_source=rss',
    date: '2026-01-10',
    year: 2026,
    outroMusic: { title: '明日へ向かって (向明天出发) - 長渕剛' }
  },

  // --- 2025 ---
  {
    id: '2025-1',
    shareRank: 1,
    title: '组织能力才是 AI 公司真正的壁垒',
    guest: 'Palona AI 联创 任川',
    description: '这是我们的第 50 期节目，也是我们今年最有成就感的一期。在 AI 时代，组织能力的重要性被大大低估了。我们把硅谷最 AI Native 的组织方式带给了大家。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/FpKYbo3ptY0NiI1GoXpAyA',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/68ccfa75a56ca3e0c438706c?utm_source=rss',
    date: '2025-09-20',
    year: 2025
  },
  {
    id: '2025-2',
    shareRank: 2,
    title: '世界加速分化下，我们的机会在哪里？',
    guest: '绿洲资本合伙人 张津剑',
    description: '津剑总能找到一些特别的角度，去拆解世界变化背后的结构性原因。这期节目，正是他在这个加速分化、噪音越来越大的时代背景下，给出的一次阶段性思考与回应。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/l_T1v1wcZ3qgF6W20c0aYQ',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/683cdd6c38dcc57c641216cb?utm_source=rss',
    date: '2025-06-02',
    year: 2025
  },
  {
    id: '2025-3',
    shareRank: 3,
    title: '关于 AI Infra 的一切',
    guest: '阶跃星辰联创 朱亦博',
    description: 'AI Infra 不仅仅是负责「降本」的后台支持，更是决定一家 AI 公司能走多远的核心战斗力。国内最懂 AI Infra 的人之一带来的「正本清源」分享。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/kYcpdBpem1UCOXamlgMZAg',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/688cc1cc8e06fe8de7d920cd?utm_source=rss',
    date: '2025-08-02',
    year: 2025
  },
  {
    id: '2025-4',
    shareRank: 4,
    title: '为什么我们对25年 AI 极度乐观｜AI 年终复盘',
    guest: 'AI 年终复盘',
    description: '24 年的市场情绪一度非常悲观，但在悲观之下，其实暗藏着不少机会。事实也证明，就像节目中提到的那样——早入场的人、乐观的人，往往会获得回报。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/wYlq_kN1xTKymPGUhLQZYA',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/6777d48a15a5fd520ecd1ea6?utm_source=rss',
    date: '2025-01-04',
    year: 2025
  },
  {
    id: '2025-5',
    shareRank: 5,
    title: 'Agent 开发的上半场: 环境、Tools 和 Context 如何决定 Agent',
    guest: 'Sheet0 创始人 王文锋',
    description: '这期可能是今年我们和从业者交流时，被提及最多的一期节目之一。我们系统讨论了与 Agent 相关的十大核心问题。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/MjrqK_PzUJPNr1m5TW4wJA',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/68032a401f1db84a563d5d83?utm_source=rss',
    date: '2025-04-19',
    year: 2025
  },
  {
    id: '2025-6',
    shareRank: 6,
    title: '一堂「强化学习」大师课',
    guest: '清华叉院助理教授 吴翼',
    description: 'DeepSeek 的发布让强化学习一度成为了必修模块。吴老师提到：人生也是一个强化学习的过程，区别是强化学习有明确的奖励函数，而人生没有。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/uce0H6JNz4PYzIIn-Xkv_A',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/67efcaf5f9578163d601286a?utm_source=rss',
    date: '2025-04-05',
    year: 2025
  },
  {
    id: '2025-7',
    shareRank: 7,
    title: '一个原教旨主义产品经理眼中的世界',
    guest: '理想 SVP 范皓宇',
    description: '这是一期充满了理想与浪漫，甚至带着点文艺气息的节目。皓宇用他的人生阅历与 25 年的产品设计经验，为我们描绘了一个「原教旨主义产品经理」眼中的世界。',
    coverImage: DEFAULT_COVER,
    link: 'http://mp.weixin.qq.com/s?__biz=MzIyMDE5OTYyMw==&mid=2651051164&idx=1&sn=8473a2630dfaf828136cf537c9927565',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/68e8a8fd525f51df3895a239?utm_source=rss',
    date: '2025-10-11',
    year: 2025,
    outroMusic: { title: 'New Boy - 朴树' }
  },
  {
    id: '2025-8',
    shareRank: 8,
    title: '我是这样用 RL + LLM 做 Agent 的',
    guest: 'Pokee AI 创始人 朱哲清 Bill',
    description: '嘉宾 Bill 曾是 Meta 应用强化学习组的负责人。如果你也想在技术发展早期就发现并把握住机会，这期节目可能会给你一些启发。',
    coverImage: DEFAULT_COVER,
    link: 'https://psee.io/8g8u7n',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/678b10ecfd38652366dc9038?utm_source=rss',
    date: '2025-01-18',
    year: 2025
  },
  {
    id: '2025-9',
    shareRank: 9,
    title: '2018 - 2020，抖音超越快手的关键三年',
    guest: 'Lessie AI 创始人 于北川',
    description: '北川曾是抖音早期的产品经理。在这期节目里，我们难得有机会从关键决策、组织文化到一线交锋，相对完整地复盘了 2018–2020 年抖音超越快手的关键三年。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/SHLK9T2FGTHEkOZeEVkrLQ',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/690d657baf4fc00da78badba?utm_source=rss',
    date: '2025-11-08',
    year: 2025,
    outroMusic: { title: 'Twilight Rush - 结冰水' }
  },
  {
    id: '2025-10',
    shareRank: 10,
    title: 'OpusClip 增长秘诀：如果每个阶段只让我选一件事做',
    guest: 'Opus 前增长产品负责人 君陶',
    description: '信息密度极高、非常实用的分享。希望能让更多人听到这套来自海外最一线的增长方法论。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/Wf-rJGrZ0Oe2-vPc_2cvrA',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/68fb18780156720321d444eb?utm_source=rss',
    date: '2025-10-25',
    year: 2025,
    outroMusic: { title: '走过咖啡屋 - 千百惠' }
  },
  {
    id: '2025-11',
    shareRank: 11,
    title: '人生就是一场大 Sales，如何做一个更好的 BD？',
    guest: '某科技家办 戴安琪',
    description: 'BD 是一项极其重要的能力，而嘉宾的分享非常具体，也足够真诚。',
    coverImage: DEFAULT_COVER,
    link: 'https://psee.io/8g8xuf',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/685f566108d8fd858662acd3?utm_source=rss',
    date: '2025-06-28',
    year: 2025
  },
  {
    id: '2025-12',
    shareRank: 12,
    title: '信念感与硅谷顶尖孵化器的奇遇：赴美三月，实现千万刀 ARR',
    guest: 'ACE Studio 创始人 Joe',
    description: '这是我们自己非常喜欢的一期节目。听完这期，你或许会发现，你和业务 3 个月翻 10 倍之间，差的可能就是「信念感」这三个字。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/N4Sqy8YRR_-ADfqewjqYbQ',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/67c1faf7bf52a16cd1b80a7c?utm_source=rss',
    date: '2025-03-01',
    year: 2025
  },
  {
    id: '2025-13',
    shareRank: 13,
    title: 'Dify 从被低估到成为明星项目，到底做对了什么',
    guest: 'Dify 创始人 路宇',
    description: 'Dify 是我们一路陪伴着成长起来的项目。从 23 年的籍籍无名，到如今成为全球 Top 的开源项目，Dify 到底做对了什么？这期节目能给出一个相对完整的答案。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/wek7dulZRYorsZwn0Oia5w',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/693285733fec3166cf688645?utm_source=rss',
    date: '2025-12-06',
    year: 2025,
    outroMusic: { title: '声音玩具 - 时间' }
  },
  {
    id: '2025-14',
    shareRank: 14,
    title: 'AI 下半场：聊透 Benchmark 与 Evaluation',
    guest: '前 Kimi 产品经理 丁丁',
    description: '定义和评估的重要性将越来越高。丁丁分享了一些有关 Benchmark 与 Evaluation 的实践与思考。',
    coverImage: DEFAULT_COVER,
    link: 'https://psee.io/8g8zb4',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/6818517a6970cc7b4db62789?utm_source=rss',
    date: '2025-05-05',
    year: 2025
  },
  {
    id: '2025-15',
    shareRank: 15,
    title: 'Mercor 高速增长的秘诀与其中的聪明人',
    guest: 'Mercor 首位中国员工 虞快',
    description: '虞快是我 8 月硅谷之行中印象最深、也最聪明的人之一。他从内部视角带我们重新认识了 Mercor，也分享了许多关于职场判断与识人之道的思考。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/gKq3a4WPEZU5gS0R74ihnQ',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/68bbf7cc5faf3686594e9534?utm_source=rss',
    date: '2025-09-06',
    year: 2025
  },
  {
    id: '2025-16',
    shareRank: 16,
    title: '硅谷 AI 大转弯与二级市场的牛市',
    guest: '莫傑麟',
    description: '他熟悉硅谷二级市场，我熟悉国内一级市场，定期凑在一起复盘 AI 市场的新变化，总能碰撞出很多趋势洞察。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/mL_lo83knttvUnhuwwxQbA',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/68a821c942cc2798e7dd1f4a?utm_source=rss',
    date: '2025-08-23',
    year: 2025
  },
  {
    id: '2025-17',
    shareRank: 17,
    title: '从 E2B 到 Browserbase，Agent Infra 新热点中有哪些大机会？',
    guest: 'Grasp 创始人 雷磊',
    description: 'Agent Infra 是今年继 Agent 应用之后的一个新热点。我们专门聊了聊这一赛道中可能涌现的机会。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/gIHoE32VuvlXlGoLe5kCpg',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/684cf1dd4abe6e29cb105710?utm_source=rss',
    date: '2025-06-14',
    year: 2025
  },
  {
    id: '2025-18',
    shareRank: 18,
    title: '关于 AI、开源、商业化与全球化的经验、教训和方法论',
    guest: 'PingCAP CTO 东旭',
    description: '东旭毫无保留地分享了他们在全球化过程中的经验、踩过的坑，以及一些已经被验证过的方法论。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/PLR-UWFrkwPrIm1jviP1_g',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/68274977457b22ce0d0dc9e9?utm_source=rss',
    date: '2025-05-17',
    year: 2025
  },
  {
    id: '2026-2',
    shareRank: 19,
    title: '中美 AI 创投的真实差异',
    guest: 'Leonis Capital 合伙人 Jenny',
    description: '在42章经工作的好处之一，就是可以了解更一线、更多元、更 insightful 的信息。这期聊中美 AI 创投差异的节目，就是一个很好的代表。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/z5VRvam9tH2cPvP7WCvfSg',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/694e181744647f77684bb4f1?utm_source=rss',
    date: '2025-12-27',
    year: 2025,
    outroMusic: { title: 'The Pied Piper - Crispian St. Peters' }
  },
  {
    id: '2025-19',
    shareRank: 20,
    title: '第一个出 ICU 的 AI 创业者',
    guest: '心影随形 CEO Binson',
    description: 'Binson 不仅聊到了产品，也聊到了许多在经历人生重大变故之后的感悟。',
    coverImage: DEFAULT_COVER,
    link: 'https://psee.io/8g948x',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/67affb07606e5c59408daf5c?utm_source=rss',
    date: '2025-02-15',
    year: 2025
  },
  {
    id: '2025-20',
    shareRank: 21,
    title: '世界怎么就「东升西落」了？聊聊二级市场与 DeepSeek+Manus 的热潮',
    guest: '莫傑麟',
    description: '聊了聊「东升西落」叙事背后的逻辑、DeepSeek & Manus 给市场带来的影响，以及当时二级市场的那波牛市。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/dOSnt8aj8S46Rp5y9HoBwQ',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/67de36c4dd11f9c8c150b8f0?utm_source=rss',
    date: '2025-03-22',
    year: 2025
  },
  {
    id: '2025-21',
    shareRank: 22,
    title: '「你觉得 AI 有泡沫吗？」——有！',
    guest: '莫傑麟',
    description: 'AI 一定有泡沫，但这并不重要。那重要的到底是什么呢？',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/UBVvDxQGQJJRjpTzTyJteA',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/692035926018cc2c98f08264?utm_source=rss',
    date: '2025-11-22',
    year: 2025,
    outroMusic: { title: '泡沫 - 花儿乐队' }
  },
  {
    id: '2025-22',
    shareRank: 23,
    title: '并购的本质',
    guest: '云磬投资创始人 立阳',
    description: '大家对「收并购」这个词并不陌生，但未必真正了解背后的资本运作逻辑。在这期节目里，我们就尝试把这件事从头到尾讲清楚。',
    coverImage: DEFAULT_COVER,
    link: 'https://psee.io/8g96qx',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/6879ead0a9dec92500eab32e?utm_source=rss',
    date: '2025-07-19',
    year: 2025
  },

  // --- 2024 ---
  {
    id: '2024-1',
    shareRank: 1,
    title: '用绝对理性应对世界的波动',
    guest: '德扑世界冠军 Ricky Mao',
    description: '这期整了个花活，和世界扑克大赛金手链得主 Ricky 一起从德扑切入，聊了聊概率、博弈、识人。很多朋友都很喜欢本期的一句金句，即 “通胀是人生的大小盲”。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/ho_ioW2w0RV7Ibv88mVuYw',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/675a56087d8426f692780f68?utm_source=rss',
    date: '2024-12-14',
    year: 2024
  },
  {
    id: '2024-2',
    shareRank: 2,
    title: '找 PMF 就是要做没壁垒的事',
    guest: '连续创业者 Albert',
    description: 'Albert 是曲老师个人非常喜欢的嘉宾。这期播客记录了他 AI 创业一年后的所思所想和认知变化，依旧很有代表性和启发性。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/Ww38EG4-e1DgAOPdidVwjg',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/66ee95306920a36bfc9f1de1?utm_source=rss',
    date: '2024-09-21',
    year: 2024
  },
  {
    id: '2024-3',
    shareRank: 3,
    title: '我在 Character.ai 做 Post Training',
    guest: '前 C.AI 模型应用算法专家 Ted',
    description: 'Ted 毫无保留地分享了美国最好的 AI 公司是如何运作的， Post Training 的最佳实践是怎么做的，以及对硅谷 AI 趋势 & 氛围的体感和思考。',
    coverImage: DEFAULT_COVER,
    link: 'https://mp.weixin.qq.com/s/Vjqp705OVDgmR-aa_uaCHA',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/67359e9843dc3a43878eaa90?utm_source=rss',
    date: '2024-11-16',
    year: 2024
  },
  {
    id: '2024-4',
    shareRank: 4,
    title: '重生之我在大厂做 AI+教育的 18 个月',
    guest: '高途 AI 产品负责人 封诚',
    description: '用上 AI 后，他们的获客转化率已经翻了一倍以上，而我相信类似的经验其实可以迁移至很多行业。',
    coverImage: DEFAULT_COVER,
    link: 'https://psee.io/6vveda',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/670a90fcdb2cf82757b990dd?utm_source=rss',
    date: '2024-10-12',
    year: 2024
  },
  {
    id: '2024-5',
    shareRank: 5,
    title: 'Cursor 刷屏背后，复盘 AI Coding 的现状与发展',
    guest: 'Gru.ai 创始人 张海龙',
    description: '海龙是国内 Coding 领域最有发言权的人之一。这期播客是一个很好的 AI Coding 基础入门。',
    coverImage: DEFAULT_COVER,
    link: 'https://psee.io/6vvgtz',
    audioUrl: 'https://www.xiaoyuzhoufm.com/episode/671c9a42eb46cd6655da1e6f?utm_source=rss',
    date: '2024-10-26',
    year: 2024
  }
];
